version: '3.1'
services:
  
  
  web:
    build: .
    command: bash -c "npm run start"
    environment:
      PORT: 4200
    volumes:
      - .:/client/
    ports:
      - "4200:4200"
 # Port required for debugging with node
      - "9876:9876"
   
volumes:
  db: {}
 